[helium]
src.github = "imputnet/helium-linux"
fetch.url = "https://github.com/imputnet/helium-linux/releases/download/$ver/helium-$ver-x86_64.AppImage"

[home-assistant]
src.container = "homeassistant/home-assistant"
src.include_regex = "\\d+\\.\\d+\\.\\d+\\.dev\\d+$"
fetch.docker = "homeassistant/home-assistant"


[music-assistant]
src.github_tag = "music-assistant/server"
src.include_regex = "\\d+\\.\\d+\\.\\d+"
fetch.url = "https://github.com/music-assistant/server/archive/refs/tags/$ver.tar.gz"

[norish]
src.container = "norishapp/norish"
src.include_regex = "v\\d+\\.\\d+\\.\\d+-beta$"
fetch.docker = "norishapp/norish"

[orca-slicer]
src.github_tag = "OrcaSlicer/OrcaSlicer"
src.include_regex = "v.*"
fetch.url = "https://github.com/OrcaSlicer/OrcaSlicer/releases/download/$ver/OrcaSlicer_Linux_AppImage_Ubuntu2404_$ver.AppImage"
