# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  helium = {
    pname = "helium";
    version = "0.10.9.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.10.9.1/helium-0.10.9.1-x86_64.AppImage";
      sha256 = "sha256-FMO4gB2zOjhgmjfE/T0XdDb0NMDKsQFuzy/Org1iD48=";
    };
  };
  home-assistant = {
    pname = "home-assistant";
    version = "2026.4.1";
    src = dockerTools.pullImage {
      imageName = "homeassistant/home-assistant";
      imageDigest = "sha256:8848691147f01a6eee7753de2ade21b04d6168fcd2e2a7089f6f84e3b7b86960";
      sha256 = "sha256-mBYDzQZycQw+Nv8kepUJvkwbLkQdGmoBkl3oMqzqf5Q=";
      finalImageTag = "2026.4.1";
    };
  };
  norish = {
    pname = "norish";
    version = "v0.17.3-beta";
    src = dockerTools.pullImage {
      imageName = "norishapp/norish";
      imageDigest = "sha256:09ca93226afadf93cf9538335b032857c28c4ad704004cc34f36cb16ae51ab14";
      sha256 = "sha256-SS8ST5kDC5NT3+RCFYOm/AuUaAnEPjw+7+q6yWNjoQw=";
      finalImageTag = "v0.17.3-beta";
    };
  };
}
